### ISSUE TITLE
ADF Tape21 parser

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#185]
**Is your feature request related to a problem? Please describe.**
ADF produces the TAPE21 files which are binary files with very specific formatting. Using the dmpkf utility that they have to convert it into an ASCII formatted file we could parse all of the data. The advantage of this is that it is less likely that there would be any changes to the format of the files along with it being universal for parsing things like atom tables which have a different format for nearly every time the atomic positions are listed.

**Describe alternatives you've considered**
Done locally.

**Comment by tjduigna** [comment]
I remember having to dissect the dmpkf generated ASCII formatted TAPE21 in order to discover a hidden normalization factor present in ADF basis function processing: https://github.com/exa-analytics/exatomic/blob/master/exatomic/adf/output.py#L156

I think this would be very useful for the reason that it was only with that file's data that the ADF orbital isosurface plotting works reasonably well at all.
