### ISSUE TITLE
Add a to_xyz bound method to Atom

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exatomic#85]
This is purely for convenience but instead of repeating 

```
atom[['symbol', 'x', 'y', 'z']].to_csv(sep=' ', float_format='%    .8f', header=False, index=False, quoting=csv.QUOTE_NONE, escapechar=' ')
```

can simply wrap that in a bound method of the atom table.

```
atom.to_xyz()

def to_xyz(self):
    return self[['symbol', 'x', 'y', 'z']].to_csv(sep=' ', float_format='%    .8f', header=False, index=False, quoting=csv.QUOTE_NONE, escapechar=' ')
```

**Comment by tjduigna** [comment]
This can be a thin wrapper around the XYZ.from_universe machinery that includes some kwargs available in the current implementation such as allowing to specify frame index (e.g. to only write the last frame of a geometry optimization), a tag (for lack of a better word) or column name to use instead of symbol (for labeled atoms etc.) and perhaps a unit kwarg.
